/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as PortfolioProjectsRouteRouteImport } from './routes/portfolio-projects/route'
import { Route as CreativeCornerRouteRouteImport } from './routes/creative-corner/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioProjectsIndexRouteImport } from './routes/portfolio-projects/index'
import { Route as CreativeCornerIndexRouteImport } from './routes/creative-corner/index'
import { Route as PortfolioProjectsSlugRouteRouteImport } from './routes/portfolio-projects/$slug/route'
import { Route as CreativeCornerSlugRouteRouteImport } from './routes/creative-corner/$slug/route'
import { Route as PortfolioProjectsSlugIndexRouteImport } from './routes/portfolio-projects/$slug/index'
import { Route as CreativeCornerSlugIndexRouteImport } from './routes/creative-corner/$slug/index'

const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectsRouteRoute = PortfolioProjectsRouteRouteImport.update({
  id: '/portfolio-projects',
  path: '/portfolio-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeCornerRouteRoute = CreativeCornerRouteRouteImport.update({
  id: '/creative-corner',
  path: '/creative-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectsIndexRoute = PortfolioProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioProjectsRouteRoute,
} as any)
const CreativeCornerIndexRoute = CreativeCornerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreativeCornerRouteRoute,
} as any)
const PortfolioProjectsSlugRouteRoute =
  PortfolioProjectsSlugRouteRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PortfolioProjectsRouteRoute,
  } as any)
const CreativeCornerSlugRouteRoute = CreativeCornerSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CreativeCornerRouteRoute,
} as any)
const PortfolioProjectsSlugIndexRoute =
  PortfolioProjectsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortfolioProjectsSlugRouteRoute,
  } as any)
const CreativeCornerSlugIndexRoute = CreativeCornerSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreativeCornerSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creative-corner': typeof CreativeCornerRouteRouteWithChildren
  '/portfolio-projects': typeof PortfolioProjectsRouteRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/creative-corner/$slug': typeof CreativeCornerSlugRouteRouteWithChildren
  '/portfolio-projects/$slug': typeof PortfolioProjectsSlugRouteRouteWithChildren
  '/creative-corner/': typeof CreativeCornerIndexRoute
  '/portfolio-projects/': typeof PortfolioProjectsIndexRoute
  '/creative-corner/$slug/': typeof CreativeCornerSlugIndexRoute
  '/portfolio-projects/$slug/': typeof PortfolioProjectsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/creative-corner': typeof CreativeCornerIndexRoute
  '/portfolio-projects': typeof PortfolioProjectsIndexRoute
  '/creative-corner/$slug': typeof CreativeCornerSlugIndexRoute
  '/portfolio-projects/$slug': typeof PortfolioProjectsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creative-corner': typeof CreativeCornerRouteRouteWithChildren
  '/portfolio-projects': typeof PortfolioProjectsRouteRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/creative-corner/$slug': typeof CreativeCornerSlugRouteRouteWithChildren
  '/portfolio-projects/$slug': typeof PortfolioProjectsSlugRouteRouteWithChildren
  '/creative-corner/': typeof CreativeCornerIndexRoute
  '/portfolio-projects/': typeof PortfolioProjectsIndexRoute
  '/creative-corner/$slug/': typeof CreativeCornerSlugIndexRoute
  '/portfolio-projects/$slug/': typeof PortfolioProjectsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creative-corner'
    | '/portfolio-projects'
    | '/about-me'
    | '/contact'
    | '/experience'
    | '/creative-corner/$slug'
    | '/portfolio-projects/$slug'
    | '/creative-corner/'
    | '/portfolio-projects/'
    | '/creative-corner/$slug/'
    | '/portfolio-projects/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/contact'
    | '/experience'
    | '/creative-corner'
    | '/portfolio-projects'
    | '/creative-corner/$slug'
    | '/portfolio-projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/creative-corner'
    | '/portfolio-projects'
    | '/about-me'
    | '/contact'
    | '/experience'
    | '/creative-corner/$slug'
    | '/portfolio-projects/$slug'
    | '/creative-corner/'
    | '/portfolio-projects/'
    | '/creative-corner/$slug/'
    | '/portfolio-projects/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreativeCornerRouteRoute: typeof CreativeCornerRouteRouteWithChildren
  PortfolioProjectsRouteRoute: typeof PortfolioProjectsRouteRouteWithChildren
  AboutMeRoute: typeof AboutMeRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-projects': {
      id: '/portfolio-projects'
      path: '/portfolio-projects'
      fullPath: '/portfolio-projects'
      preLoaderRoute: typeof PortfolioProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-corner': {
      id: '/creative-corner'
      path: '/creative-corner'
      fullPath: '/creative-corner'
      preLoaderRoute: typeof CreativeCornerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-projects/': {
      id: '/portfolio-projects/'
      path: '/'
      fullPath: '/portfolio-projects/'
      preLoaderRoute: typeof PortfolioProjectsIndexRouteImport
      parentRoute: typeof PortfolioProjectsRouteRoute
    }
    '/creative-corner/': {
      id: '/creative-corner/'
      path: '/'
      fullPath: '/creative-corner/'
      preLoaderRoute: typeof CreativeCornerIndexRouteImport
      parentRoute: typeof CreativeCornerRouteRoute
    }
    '/portfolio-projects/$slug': {
      id: '/portfolio-projects/$slug'
      path: '/$slug'
      fullPath: '/portfolio-projects/$slug'
      preLoaderRoute: typeof PortfolioProjectsSlugRouteRouteImport
      parentRoute: typeof PortfolioProjectsRouteRoute
    }
    '/creative-corner/$slug': {
      id: '/creative-corner/$slug'
      path: '/$slug'
      fullPath: '/creative-corner/$slug'
      preLoaderRoute: typeof CreativeCornerSlugRouteRouteImport
      parentRoute: typeof CreativeCornerRouteRoute
    }
    '/portfolio-projects/$slug/': {
      id: '/portfolio-projects/$slug/'
      path: '/'
      fullPath: '/portfolio-projects/$slug/'
      preLoaderRoute: typeof PortfolioProjectsSlugIndexRouteImport
      parentRoute: typeof PortfolioProjectsSlugRouteRoute
    }
    '/creative-corner/$slug/': {
      id: '/creative-corner/$slug/'
      path: '/'
      fullPath: '/creative-corner/$slug/'
      preLoaderRoute: typeof CreativeCornerSlugIndexRouteImport
      parentRoute: typeof CreativeCornerSlugRouteRoute
    }
  }
}

interface CreativeCornerSlugRouteRouteChildren {
  CreativeCornerSlugIndexRoute: typeof CreativeCornerSlugIndexRoute
}

const CreativeCornerSlugRouteRouteChildren: CreativeCornerSlugRouteRouteChildren =
  {
    CreativeCornerSlugIndexRoute: CreativeCornerSlugIndexRoute,
  }

const CreativeCornerSlugRouteRouteWithChildren =
  CreativeCornerSlugRouteRoute._addFileChildren(
    CreativeCornerSlugRouteRouteChildren,
  )

interface CreativeCornerRouteRouteChildren {
  CreativeCornerSlugRouteRoute: typeof CreativeCornerSlugRouteRouteWithChildren
  CreativeCornerIndexRoute: typeof CreativeCornerIndexRoute
}

const CreativeCornerRouteRouteChildren: CreativeCornerRouteRouteChildren = {
  CreativeCornerSlugRouteRoute: CreativeCornerSlugRouteRouteWithChildren,
  CreativeCornerIndexRoute: CreativeCornerIndexRoute,
}

const CreativeCornerRouteRouteWithChildren =
  CreativeCornerRouteRoute._addFileChildren(CreativeCornerRouteRouteChildren)

interface PortfolioProjectsSlugRouteRouteChildren {
  PortfolioProjectsSlugIndexRoute: typeof PortfolioProjectsSlugIndexRoute
}

const PortfolioProjectsSlugRouteRouteChildren: PortfolioProjectsSlugRouteRouteChildren =
  {
    PortfolioProjectsSlugIndexRoute: PortfolioProjectsSlugIndexRoute,
  }

const PortfolioProjectsSlugRouteRouteWithChildren =
  PortfolioProjectsSlugRouteRoute._addFileChildren(
    PortfolioProjectsSlugRouteRouteChildren,
  )

interface PortfolioProjectsRouteRouteChildren {
  PortfolioProjectsSlugRouteRoute: typeof PortfolioProjectsSlugRouteRouteWithChildren
  PortfolioProjectsIndexRoute: typeof PortfolioProjectsIndexRoute
}

const PortfolioProjectsRouteRouteChildren: PortfolioProjectsRouteRouteChildren =
  {
    PortfolioProjectsSlugRouteRoute:
      PortfolioProjectsSlugRouteRouteWithChildren,
    PortfolioProjectsIndexRoute: PortfolioProjectsIndexRoute,
  }

const PortfolioProjectsRouteRouteWithChildren =
  PortfolioProjectsRouteRoute._addFileChildren(
    PortfolioProjectsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreativeCornerRouteRoute: CreativeCornerRouteRouteWithChildren,
  PortfolioProjectsRouteRoute: PortfolioProjectsRouteRouteWithChildren,
  AboutMeRoute: AboutMeRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
