/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreativeCornerIndexRouteImport } from './routes/creative-corner/index'
import { Route as CreativeCornerSlugRouteImport } from './routes/creative-corner/$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeCornerIndexRoute = CreativeCornerIndexRouteImport.update({
  id: '/creative-corner/',
  path: '/creative-corner/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeCornerSlugRoute = CreativeCornerSlugRouteImport.update({
  id: '/creative-corner/$slug',
  path: '/creative-corner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/creative-corner/$slug': typeof CreativeCornerSlugRoute
  '/creative-corner': typeof CreativeCornerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/creative-corner/$slug': typeof CreativeCornerSlugRoute
  '/creative-corner': typeof CreativeCornerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/creative-corner/$slug': typeof CreativeCornerSlugRoute
  '/creative-corner/': typeof CreativeCornerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/contact'
    | '/creative-corner/$slug'
    | '/creative-corner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/contact'
    | '/creative-corner/$slug'
    | '/creative-corner'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/contact'
    | '/creative-corner/$slug'
    | '/creative-corner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  ContactRoute: typeof ContactRoute
  CreativeCornerSlugRoute: typeof CreativeCornerSlugRoute
  CreativeCornerIndexRoute: typeof CreativeCornerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-corner/': {
      id: '/creative-corner/'
      path: '/creative-corner'
      fullPath: '/creative-corner'
      preLoaderRoute: typeof CreativeCornerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-corner/$slug': {
      id: '/creative-corner/$slug'
      path: '/creative-corner/$slug'
      fullPath: '/creative-corner/$slug'
      preLoaderRoute: typeof CreativeCornerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  ContactRoute: ContactRoute,
  CreativeCornerSlugRoute: CreativeCornerSlugRoute,
  CreativeCornerIndexRoute: CreativeCornerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
